# Generated by Django 2.1.2 on 2018-10-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=750)),
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
